use_frameworks!

target 'PodComponent_Example' do
  pod 'PodComponent', :path => '../'

  target 'PodComponent_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
